### ISSUE TITLE
Error during evaluation

### ISSUE THREAD

**Issue by RainbowRui** [zju3dv/TotalSelfScan#3]
Dear authors,

When I run the evaluation code:`python run.py --type visualize --cfg_file configs/anisdf_zju_djt415_tshirt.yaml exp_name release_tshirt_face_bound0.1 resume True vis_tpose_mesh True vis_face_mesh True num_train_frame 1 train.num_workers 0 part_type 1 gpus 1, debug.single_part True debug.transform_face False`,
I encounter an error `FileNotFoundError: [Errno 2] No such file or directory: 'data/smplx/smplh/SMPLH_MALE.pkl'`.

So are there some files I have not prepared? Thanks!

**Comment by jiayaozhang** [comment]
You can get the dataset `smplx/smplh/SMPLH_MALE.pkl` from here
`https://mano.is.tue.mpg.de/index.html`

also for me, base_utils.py line 8 need to add encoding='bytes' in order to make it work
```python
def read_pickle(pkl_path):
    with open(pkl_path, 'rb') as f:
        return pickle.load(f, encoding='bytes')
```

But I encounter another error and may need help

```python

  select_label = stats.mode(labels)[0][0]
  0%|                                                                                                                                                                                                                    | 0/1 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "/home/janice/Documents/TotalSelfScan/run.py", line 145, in <module>
    globals()['run_' + args.type]()
  File "/home/janice/Documents/TotalSelfScan/run.py", line 102, in run_visualize
    output = renderer.render(batch)
  File "/home/janice/Documents/TotalSelfScan/lib/networks/renderer/sdf_mesh_renderer.py", line 175, in render
    blend_weights = self.sample_bw_closest_face(pts, batch)
  File "/home/janice/Documents/TotalSelfScan/lib/networks/renderer/sdf_mesh_renderer.py", line 199, in sample_bw_closest_face
    smplh_bw = smplh['weights'].astype(np.float32)
KeyError: 'weights'


```

**Comment by DongJT1996** [comment]
Please check if the file SMPLH_MALE.pkl is correct.
